#
# Webproject NG
# Copyright © 2021 - 2022 Gmasil
#
# This file is part of Webproject NG.
#
# Webproject NG is licensed under the Creative Commons
# Attribution-NonCommercial-ShareAlike 4.0 International
# Public License ("Public License").
#
# Webproject NG is non-free software: you can redistribute
# it and/or modify it under the terms of the Public License.
#
# You should have received a copy of the Public License along
# with Webproject NG. If not, see
# https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt
#

server:
  port: 6900
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
  error:
    path: /error

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      load-on-startup: 1
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  data:
    rest:
      base-path: api

app:
  access:
    public: false

dataimport:
  enabled: false
  file: data.yml
  clean: false

init:
  skip: false
  admin:
    name: "admin"
    password: "admin"
  theme:
    name: "Default"
    background-color: "#ffffff"
    background-highlight-color: "#f2f2f2"
    primary-color: "#ad0707"
    secondary-color: "#5e0000"
    text-color: "#171717"
